
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14-jessie
    working_directory: ~/circleci-tools

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            virtualenv venv
            venv/bin/pip install -r requirements.txt
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            mkdir test_results
            nosetests --xunitmp-file=test_results/nose.xml --with-xunitmp
      - store_test_results:
          path: test_results

