
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:2.7.14-jessie
    working_directory: ~/circleci-tools

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            virtualenv venv
            venv/bin/pip install -r requirements.txt
            . venv/bin/activate
      - run:
          name: run tests
          command: nosetests
      - store_artifacts:
          path: test-reports
          destination: test-reports

